name: image_converter
description: Simple command-line application to transform images and PDF's to resized jpg's images built with Dart.
version: 1.2.6
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  mocktail: ^0.3.0
  test: ^1.24.0
dependencies:
  diacritic: ^0.1.3
  dotenv: ^4.1.0
  image: ^4.0.15
  mime: ^1.0.4
  path: ^1.8.3
  pdfium_bindings: ^2.0.1
