name: image_converter
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  diacritic: ^0.1.3
  dotenv: ^4.1.0
  image: ^4.0.15
  mime: ^1.0.4
  path: ^1.8.3
  pdfium_bindings: ^2.0.0
