name: Build and Release

on:
  push:
    branches: ["main"]
    paths:
      - 'bin/**'
      - 'lib/**'
      - 'test/**'
      - '**.so'
      - '**.dll'

env:
  VERSION_NUMBER: 1.1.3

jobs:
  test-and-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test

      - name: Clear linux binary folder
        if: matrix.os == 'ubuntu-latest'
        run: |
          find binaries ! -name '.gitkeep' -type f -exec rm -f {} +
      - name: Clear windows binary folder
        if: matrix.os == 'windows-latest'
        run: |
          Get-ChildItem -Path binaries -Recurse -File -Exclude .gitkeep -Force | Remove-Item -Recurse -Force

      - name: Compile linux executable
        if: matrix.os == 'ubuntu-latest'
        run: |
          dart compile exe bin/main.dart -o binaries/linux/v${{ env.VERSION_NUMBER }}-x64
      - name: Compile windows executable
        if: matrix.os == 'windows-latest'
        run: |
          dart compile exe bin/main.dart -o binaries/windows/v${{ env.VERSION_NUMBER }}-x64.exe

      - name: Upload compiled files
        if: ${{ job.status == 'success' }}
        uses: actions/upload-artifact@v3
        with:
          name: compiled-files
          path: binaries/

  create-release:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: ${{ needs.test-and-build.result == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - name: Remove all binaries
        run: |
          rm -rf binaries

      - name: Download compiled files
        uses: actions/download-artifact@v3
        with:
          name: compiled-files
          path: binaries/

      - name: Make executable binary files
        run: |
          find binaries ! -name '.gitkeep' -type f -exec chmod +x {} +

      - name: Increase version in files
        run: |
          sed -i "s/version:.*/version: ${{ env.VERSION_NUMBER }}/g" pubspec.yaml
          sed -i "s/binaries\/linux\/[^;]*/binaries\/linux\/v${{ env.VERSION_NUMBER }}-x64/g" run_linux-x64.sh
          sed -i 's/binaries\\windows\\[^-]*-x64.exe/binaries\\windows\\v${{ env.VERSION_NUMBER }}-x64.exe/g' run_win-x64.bat

      - name: Add and commit compiled files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Upgrade to version v${{ env.VERSION_NUMBER }}"
          git tag v${{ env.VERSION_NUMBER }}
          git push origin HEAD --tags

      - name: Create and publish release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION_NUMBER }}