name: Build and Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  VERSION: "v1.1.1"

jobs:
  test-and-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test

      - name: Clear linux binary folder
        if: matrix.os == 'ubuntu-latest'
        run: |
          find binaries/linux ! -name '.gitkeep' -type f -exec rm -f {} +

      - name: Clear windows binary folder
        if: matrix.os == 'windows-latest'
        run: |
          Get-ChildItem -Path binaries/windows -Exclude .gitkeep -Force | Remove-Item -Recurse -Force

      - name: Compile executable
        run: |
          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            dart compile exe bin/main.dart -o binaries/linux/${{ env.VERSION }}-x64
          elif [ ${{ matrix.os }} == 'windows-latest' ]; then
            dart compile exe bin/main.dart -o binaries/windows/${{ env.VERSION }}-x64.exe
          fi

      - name: Add and commit compiled files
        if: ${{ job.status == 'success' }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add binaries/
          git commit -m "Compiled executable files for version ${{ env.VERSION }} for ${{ matrix.os }}"

  create-release:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: ${{ needs.test-and-build.result == 'success' }}
    steps:
      - name: Create and publish release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          automatic_release_tag: ${{ env.VERSION }}
          prerelease: false
          title: Release ${{ env.VERSION }}