name: PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.dart"
      - "**.so"
      - "**.dll"
      - "pubspec.yaml"
      - "pubspec.lock"
      - ".github/workflows/*.yml"

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get the version number
        id: get_version_number
        uses: mikefarah/yq@master
        with:
          cmd: yq '.env.["VERSION_NUMBER"]' '.github/workflows/ci.yml'

      - name: Check if the version on CI is different of the latest release
        run: |
          REMOTE=$(git ls-remote --tags origin "v${{ steps.get_version_number.outputs.result }}" | wc -l)
          if [ "${REMOTE}" -ne "0" ]; then
            echo "Tag already exists. Please update VERSION_NUMBER."
            exit 1
          fi

  pr-review:
    needs: check-version
    if: ${{ needs.check-version.result == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - id: restore-cache-deps
        name: Restore Cache dependencies
        uses: actions/cache/restore@v3
        with:
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          path: ~/.pub-cache

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Save Cache dependencies
        uses: actions/cache/save@v3
        if: steps.restore-cache-deps.outputs.cache-hit != 'true'
        with:
          key: ${{ steps.restore-cache-deps.outputs.cache-primary-key }}
          path: ~/.pub-cache

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test
