name: PR Review Workflow

on:
  pull_request:
    types: [reopened, ready_for_review]
    paths:
      - "**.dart"
      - "**.so"
      - "**.dll"
      - "pubspec.yaml"
      - "pubspec.lock"

jobs:
  pr-review:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - id: restore-cache-deps
        name: Restore Cache dependencies
        uses: actions/cache/restore@v3
        with:
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          path: |
            ~/.pub-cache
            .dart-tool

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        if: steps.restore-cache-deps.outputs.cache-hit != 'true'
        run: dart pub get

      - name: Save Cache dependencies
        uses: actions/cache/save@v3
        if: steps.restore-cache-deps.outputs.cache-hit != 'true'
        with:
          key: ${{ steps.restore-cache-deps.outputs.cache-primary-key }}
          path: |
            ~/.pub-cache
            .dart-tool

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test
