name: PR Review

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - "**.dart"
      - "**.so"
      - "**.dll"
      - "pubspec.lock"
      - ".github/workflows/*.yml"

jobs:
  check-version:
    if: github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/check-version.yml

  analyze_and_test:
    needs: check-version
    if: always() && (needs.check-version.result == 'success' || needs.check-version.result == 'skipped')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: restore-cache-deps
        name: Restore Cache dependencies
        uses: actions/cache/restore@v3
        with:
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          path: ~/.pub-cache

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Save Cache dependencies
        uses: actions/cache/save@v3
        if: steps.restore-cache-deps.outputs.cache-hit != 'true'
        with:
          key: ${{ steps.restore-cache-deps.outputs.cache-primary-key }}
          path: ~/.pub-cache

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test
